In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [18]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [19]:
#define Vocabulary Size
voc_size = 10000

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
### One Hot representation

one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[5730, 4383, 8946, 1316],
 [5730, 4383, 8946, 9953],
 [5730, 9563, 8946, 4509],
 [9574, 3226, 4002, 2114, 1558],
 [9574, 3226, 4002, 2114, 702],
 [7165, 5730, 306, 8946, 8431],
 [253, 8713, 4749, 2114]]

In [22]:
## Word Embeddings representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [23]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

print(embedded_docs)

[[   0    0    0    0 5730 4383 8946 1316]
 [   0    0    0    0 5730 4383 8946 9953]
 [   0    0    0    0 5730 9563 8946 4509]
 [   0    0    0 9574 3226 4002 2114 1558]
 [   0    0    0 9574 3226 4002 2114  702]
 [   0    0    0 7165 5730  306 8946 8431]
 [   0    0    0    0  253 8713 4749 2114]]


In [24]:
dim = 10

In [25]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

/opt/miniconda3/envs/ai_learning/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [26]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [36]:
embedded_vector = model.predict(embedded_docs)

embedded_vector.shape

print(embedded_vector)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[[[ 0.0177376  -0.00503905 -0.02693065  0.01385817  0.0145051
   -0.03122346 -0.00392245  0.01456114 -0.00418434 -0.00234313]
  [ 0.0177376  -0.00503905 -0.02693065  0.01385817  0.0145051
   -0.03122346 -0.00392245  0.01456114 -0.00418434 -0.00234313]
  [ 0.0177376  -0.00503905 -0.02693065  0.01385817  0.0145051
   -0.03122346 -0.00392245  0.01456114 -0.00418434 -0.00234313]
  [ 0.0177376  -0.00503905 -0.02693065  0.01385817  0.0145051
   -0.03122346 -0.00392245  0.01456114 -0.00418434 -0.00234313]
  [-0.02174755 -0.03863511 -0.04028773  0.01254285  0.02336583
   -0.03304311 -0.03164063 -0.01976442 -0.00707415  0.0157174 ]
  [ 0.0036859   0.04043316  0.01588968 -0.02499943  0.02778291
    0.03285545  0.02240903  0.04491825  0.01109748  0.00948237]
  [-0.01822593 -0.00091715  0.02583673  0.00734568 -0.02149671
   -0.00757669  0.03951671  0.01032295 -0.0239262   0.01870915]
  [ 0.02604356  0.01195509 -0.03601564  0.02529768  0.02271834
    0.02295284

In [28]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)